//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Web_portal.LibraryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryService.ILibraryService")]
    public interface ILibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/InsertUpdateUserDetails", ReplyAction="http://tempuri.org/ILibraryService/InsertUpdateUserDetailsResponse")]
        string InsertUpdateUserDetails(Library_System_Web_portal_Service.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/InsertUpdateUserDetails", ReplyAction="http://tempuri.org/ILibraryService/InsertUpdateUserDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUpdateUserDetailsAsync(Library_System_Web_portal_Service.SignUp signUp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : Library_System_Web_portal.LibraryService.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<Library_System_Web_portal.LibraryService.ILibraryService>, Library_System_Web_portal.LibraryService.ILibraryService {
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUpdateUserDetails(Library_System_Web_portal_Service.SignUp signUp) {
            return base.Channel.InsertUpdateUserDetails(signUp);
        }
        
        public System.Threading.Tasks.Task<string> InsertUpdateUserDetailsAsync(Library_System_Web_portal_Service.SignUp signUp) {
            return base.Channel.InsertUpdateUserDetailsAsync(signUp);
        }
    }
}
