//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Web_portal.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUpdateUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUpdateUserDetailsResponse")]
        string InsertUpdateUserDetails(Library_System_Web_portal_Service.SignUp signUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUpdateUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUpdateUserDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUpdateUserDetailsAsync(Library_System_Web_portal_Service.SignUp signUp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Library_System_Web_portal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Library_System_Web_portal.ServiceReference1.IService1>, Library_System_Web_portal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUpdateUserDetails(Library_System_Web_portal_Service.SignUp signUp) {
            return base.Channel.InsertUpdateUserDetails(signUp);
        }
        
        public System.Threading.Tasks.Task<string> InsertUpdateUserDetailsAsync(Library_System_Web_portal_Service.SignUp signUp) {
            return base.Channel.InsertUpdateUserDetailsAsync(signUp);
        }
    }
}
