--  INSERT INTO LIB_MEMBER_MASTER (FMEMBER_ID,FPASSWORD,FACCOUNT_STATUS,
-- FFULL_NAME,FDOB,   FCONTACT_NO, FEMAIL, FSTATE, FCITY, FPINCODE,
-- FULL_ADDRESS)  VALUES('user4','asdf',
-- 'Pending','asdf','','','','',  
-- '','','');  SELECT LAST_INSERT_ID(); 
 -- select * from LIB_AUTHOR_MASTER;
--  INSERT INTO LIB_AUTHOR_MASTER (FAUTHOR_ID, FAUTHOR_NAME) 
--   VALUES ('l2','Chetan Bhagath')
-- SELECT
-- IFNULL(FAUTHOR_ID,'') AS FAUTHOR_ID, IFNULL(FAUTHOR_NAME,'') AS FAUTHOR_NAME 
--  FROM LIB_AUTHOR_MASTER
--  WHERE FAUTHOR_ID='l1'
-- SELECT FAUTHOR_ID FROM LIB_AUTHOR_MASTER LIMIT 0 , 3;

SET @ROW_NUMBER=0;
SELECT IFNULL(FAUTHOR_ID,'') AS FAUTHOR_ID,
(@ROW_NUMBER := @ROW_NUMBER +1) as ROWNUM,
 IFNULL(FAUTHOR_NAME,'') AS FAUTHOR_NAME
FROM LIB_AUTHOR_MASTER
-- WHERE FAUTHOR_ID='l1'
ORDER BY LENGTH(FAUTHOR_ID) ,  ROWNUM  LIMIT 0,4;

